version: '3.8'  # Для Docker Compose v2

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: matcher
      POSTGRES_PASSWORD: matcher
      POSTGRES_DB: matcher
    ports:
      - "5432:5432"
    volumes:
      - matcher_pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: matcher-minio
      MINIO_ROOT_PASSWORD: matcher-minio
      MINIO_BUCKETS: matcher-photo
    volumes:
      - minio-storage:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  kibana:
    image: kibana:7.16.1
    ports:
      - "5601:5601"
    volumes:
      - ./config/kibana/config.yml:/usr/share/kibana/config/kibana.yml:ro
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:7.16.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      ELASTIC_USERNAME: "elastic"
      ELASTIC_PASSWORD: "elastic"
      discovery.type: single-node
    volumes:
      - ./config/elasticsearch/config.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./docker_volumes/elasticsearch/data:/usr/share/elasticsearch/data

  logstash:
    image: logstash:7.16.2
    ports:
      - "5046:5046"
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    volumes:
      - ./config/logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./config/logstash/pipelines:/usr/share/logstash/config/pipelines:ro
      - ./log:/usr/share/logstash/input
    depends_on:
      - elasticsearch

volumes:
  matcher_pgdata:
  minio-storage:
