spring:
  application:
    name: matcher

  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: matcher
    password: matcher
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # или validate / none / create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
