spring:
  application:
    name: matcher

  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: matcher
    password: matcher
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate # или validate / none / create-drop
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
minio:
  url: http://localhost:9000
  access-key: matcher-minio
  secret-key: matcher-minio
  bucket-name: matcher-photo

feign:
  client:
    config:
      recognize-client:
        url: http://localhost:5555

logging:
  level:
    com.netflix.client: DEBUG  # Для отладки Feign клиента
    feign: DEBUG               # Для отладки запросов и ответов Feign
